application: db-drivertools-0002
version: 1
runtime: php
api_version: 1
  
handlers:
- url: /main
  script: main.php
  
  - url: /signup
  script: signup.php
  
  - url: /login
  script: login.php
  
  - url: /logbook
  script: logbook.php
  
  - url: /retrievelogs
  script: retrievelogs.php
  
  - url: /updatelogbook
  script: updatelogbook.php
  
  - url: /updatelogin
  script: updatelogin.php

